Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.provider "virtualbox" do |v|
        v.name = "dwdb-mongodb"
        v.cpus = 2
        v.memory = 1024
    end

    # PostgreSQL configuration
    # Learn more: https://github.com/jackdb/pg-app-dev-vm
    config.vm.provision :shell, :path => "provision.sh"
    config.vm.network :forwarded_port, guest: 27017, host: 27017

end