VAGRANTFILE_API_VERSION ||= "2"

# https://github.com/troysandal/mysql8-vagrant
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network :forwarded_port, guest: 3306, host: 13306
  config.vm.provision :shell, :path => "provision.sh"
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.provider "virtualbox" do |v|
    v.name = "dwdb-mysql"
    v.memory = 2048
    v.cpus = 1
  end
end